project:
  type: website
  output-dir: docs

website:
  title: "Tanu Tiwari"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
        
    right: 
      - href: resume.qmd
        text: Resume
      - href: Introduction.ipynb
        text: Blogs
    tools:
      - icon: twitter
        href: https://x.com/TanuTiwari7999
      - icon: github
        href: https://github.com/TanuTiwari4722
      - icon: linkedin
        href: https://www.linkedin.com/in/tanu-t-64593b141

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
